In [1]:
import numpy as np
import autograd.numpy as np
from autograd import jacobian
import sys
sys.path.append("..")
from sghmc.sghmc import sghmc

In [2]:
def U(theta, x, weight):
    '''Define the U(theta, x)'''
    
    log_prior = -0.5 * theta.T @ theta
    
    lik = 0.0
    for i in range(theta.shape[0]):
        lik += np.exp(-0.5 * (theta[i] - x)**2)
    
    log_lik = np.log(0.5 * lik)
    
    return -(log_prior + weight * np.sum(log_lik))

In [3]:
gradU = jacobian(U, argnum = 0)

In [4]:
# data
N = 500
bs = 100
dat = np.random.randn(2 * N).reshape((N, 2))
theta0 = np.zeros((3), dtype = 'float64')
Vhat = np.array([[1, 0.5, 1],[0.5, 1, 0], [1, 1, 0.5]], dtype = 'float64')

In [5]:
samples = sghmc(dat, bs, theta0, gradU, Vhat)
print(samples)

[[0.00108054 0.00893225 0.02354829]
 [0.00769136 0.02990489 0.02262358]
 [0.03251645 0.03890985 0.03059237]
 [0.03319625 0.04518625 0.05413198]
 [0.03243587 0.06708466 0.06254516]
 [0.03254429 0.08436611 0.07874371]
 [0.05060957 0.09658347 0.07623829]
 [0.07432147 0.09447731 0.08271905]
 [0.06919879 0.1078438  0.08973763]
 [0.07698037 0.12053647 0.10695227]
 [0.07951033 0.13242265 0.11278485]
 [0.09049513 0.13530624 0.12652497]
 [0.0993919  0.14109015 0.12390052]
 [0.09010548 0.15717411 0.12346693]
 [0.09212824 0.16594409 0.13287794]
 [0.08671733 0.17190443 0.13741519]
 [0.10486457 0.17072221 0.13551099]
 [0.1110943  0.17402445 0.12876064]
 [0.1216702  0.18024935 0.12044509]
 [0.14030499 0.18828035 0.12134236]
 [0.13950197 0.20176752 0.11569047]
 [0.13548844 0.1969054  0.120357  ]
 [0.13553655 0.19717928 0.11881083]
 [0.15184777 0.19601632 0.11234221]
 [0.15627916 0.19694347 0.11183994]
 [0.15729591 0.19434875 0.11437904]
 [0.15854648 0.20842364 0.1203154 ]
 [0.16076157 0.21465399 0.12