In [1]:
import numpy as np
import autograd.numpy as np
from autograd import jacobian
import sys
sys.path.append("..")
from sghmc.sghmc import sghmc

In [2]:
def U(theta, x, weight):
    '''Define the U(theta, x)'''
    
    log_prior = -0.5 * theta.T @ theta
    
    lik = 0.0
    for i in range(theta.shape[0]):
        lik += np.exp(-0.5 * (theta[i] - x)**2)
    
    log_lik = np.log(0.5 * lik)
    
    return -(log_prior + weight * np.sum(log_lik))

In [3]:
gradU = jacobian(U, argnum = 0)

In [10]:
# data
N = 500
bs = 100
dat = np.random.randn(2 * N).reshape((N, 2))
theta0 = np.zeros((3), dtype = 'float64')
Vhat = np.array([[1, 0.5, 1],[0.5, 1, 0], [1, 1, 0.5]], dtype = 'float64')

In [11]:
samples = sghmc(dat, bs, theta0, gradU, Vhat)
print(samples)

[[ 5.58648869e-03  5.46089962e-03  9.20340980e-03]
 [ 9.23425781e-03  2.32364325e-04  1.72310801e-02]
 [ 1.18733528e-02  1.61662619e-03  1.88625897e-02]
 [ 2.17357985e-02 -4.64313968e-03  2.13016016e-02]
 [ 2.93856198e-02  8.28518971e-05  2.30545354e-02]
 [ 3.55247908e-02  9.36318135e-03  3.45173658e-02]
 [ 5.01990453e-02  1.26012407e-02  3.87531025e-02]
 [ 5.83200446e-02  1.04517196e-02  4.26705910e-02]
 [ 6.96281835e-02  1.86021756e-02  4.58558561e-02]
 [ 6.33237189e-02  2.13593891e-02  5.32373845e-02]
 [ 6.32009607e-02  2.86569656e-02  5.64938804e-02]
 [ 7.85644865e-02  3.30501057e-02  6.30874976e-02]
 [ 8.68713527e-02  3.50148861e-02  6.92865363e-02]
 [ 8.75945547e-02  3.38375016e-02  7.56195798e-02]
 [ 8.39781240e-02  4.80560143e-02  7.38980573e-02]
 [ 8.88734083e-02  4.44221828e-02  8.04219191e-02]
 [ 8.98853880e-02  5.35111224e-02  8.69058187e-02]
 [ 9.06403627e-02  5.88044487e-02  8.97335180e-02]
 [ 9.35439833e-02  6.98247771e-02  1.06560581e-01]
 [ 9.76721508e-02  7.09781058e-